Exclude FragmentedFinished from FIPS 140-3 strict
The FragmentedFinished test from FIPS 140-3 strict profile can be
excluded since this environment does not allow for the PKCS12
algorithm. The test is currently failing as follows:

```
java.security.KeyStoreException: pkcs12 not found
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:873)
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:873)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:56)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:56)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:106)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:106)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:119)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:119)
	at DTLSOverDatagram.getDTLSContext(DTLSOverDatagram.java:513)
	at DTLSOverDatagram.getDTLSContext(DTLSOverDatagram.java:513)
	at DTLSOverDatagram.createSSLEngine(DTLSOverDatagram.java:135)
	at DTLSOverDatagram.createSSLEngine(DTLSOverDatagram.java:135)
	at FragmentedFinished.createSSLEngine(FragmentedFinished.java:53)
	at FragmentedFinished.createSSLEngine(FragmentedFinished.java:53)
	at DTLSOverDatagram.doServerSide(DTLSOverDatagram.java:98)
	at DTLSOverDatagram.runServer(DTLSOverDatagram.java:561)
	at DTLSOverDatagram.doClientSide(DTLSOverDatagram.java:118)
	at DTLSOverDatagram.lambda$runTest$0(DTLSOverDatagram.java:548)
	at DTLSOverDatagram.runClient(DTLSOverDatagram.java:582)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at DTLSOverDatagram.runTest(DTLSOverDatagram.java:552)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at FragmentedFinished.main(FragmentedFinished.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1595)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
Caused by: java.security.NoSuchAlgorithmException: pkcs12 KeyStore not available
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.base/java.lang.Thread.run(Thread.java:1595)
	at java.base/java.security.Security.getImpl(Security.java:743)
Caused by: 	at java.base/java.security.KeyStore.getInstance(KeyStore.java:870)
	... 13 more
java.security.NoSuchAlgorithmException: pkcs12 KeyStore not available
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.base/java.security.Security.getImpl(Security.java:743)
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:870)
	... 14 more
java.security.KeyStoreException: pkcs12 not found
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:873)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:56)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:106)
	at jdk.test.lib.security.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:119)
	at DTLSOverDatagram.getDTLSContext(DTLSOverDatagram.java:513)
	at DTLSOverDatagram.createSSLEngine(DTLSOverDatagram.java:135)
	at FragmentedFinished.createSSLEngine(FragmentedFinished.java:53)
	at DTLSOverDatagram.doClientSide(DTLSOverDatagram.java:118)
	at DTLSOverDatagram.runClient(DTLSOverDatagram.java:582)
	at DTLSOverDatagram.runTest(DTLSOverDatagram.java:552)
	at FragmentedFinished.main(FragmentedFinished.java:48)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1595)
Caused by: java.security.NoSuchAlgorithmException: pkcs12 KeyStore not available
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.base/java.security.Security.getImpl(Security.java:743)
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:870)
	... 14 more
````

This test was failing previously and excluded in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1152
however in that case a mixture of PKCS12 algorithm with JKS file caused
a different stack trace and behavior.

Signed-off-by: Jason Katonica <katonica@us.ibm.com>